ARG version
FROM almalinux:${version:-9}
ARG "Module"="Docker" \
    "Concept"="Docker Architecture" \
    "Command"="ARG"
RUN echo "Module is: ${Module},concept is: ${Concept}, Command is: ${Command}"
CMD ["sleep","infinity"]