ARG version
FROM almalinux:${version:-9}
ARG "module"="Docker" \
    "concept"="Docker Architecture" \
    "command"="ARG"
LABEL "Module"="Docker" \
      "Concept"="Docker Architecture" \
      "Command"="ARG"
RUN echo "Module is: ${module},concept is: ${concept}, Command is: ${command}"
CMD ["sleep","infinity"]